--liquibase formatted sql

--changeset avazbek:001-init-auth
--comment: Auth module — roles, permission, role_permissions, users tables

CREATE TABLE roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP,
    CONSTRAINT uq_roles_name UNIQUE (name)
);

CREATE TABLE permission
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP,
    CONSTRAINT uq_permission_code UNIQUE (code)
);

CREATE TABLE role_permissions
(
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id)
        REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id)
        REFERENCES permission (id) ON DELETE CASCADE
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(255),
    role_id       BIGINT,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_users_role FOREIGN KEY (role_id)
        REFERENCES roles (id)
);

-- Partial unique index instead of a plain UNIQUE constraint: users are soft-deleted
-- (active=false), so the same email must be re-usable for a new registration
-- after the previous account was "deleted".
CREATE UNIQUE INDEX ux_users_email_active ON users (email) WHERE active = true;

--rollback DROP TABLE users;
--rollback DROP TABLE role_permissions;
--rollback DROP TABLE permission;
--rollback DROP TABLE roles;

--changeset avazbek:002-seed-auth-data
--comment: Seed base roles and permissions, grant all permissions to ADMIN

INSERT INTO roles (name, description, active, created_at)
VALUES ('BUYER', 'Buyer role', true, CURRENT_TIMESTAMP),
       ('SELLER', 'Seller role', true, CURRENT_TIMESTAMP),
       ('ADMIN', 'Administrator role', true, CURRENT_TIMESTAMP);

INSERT INTO permission (code, description, active, created_at)
VALUES ('ROLE_VIEW', 'View roles', true, CURRENT_TIMESTAMP),
       ('PERMISSION_VIEW', 'View permissions', true, CURRENT_TIMESTAMP),
       ('ROLE_MANAGE', 'Manage roles', true, CURRENT_TIMESTAMP);

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r,
     permission p
WHERE r.name = 'ADMIN'
  AND p.code IN ('ROLE_VIEW', 'PERMISSION_VIEW', 'ROLE_MANAGE');

--rollback DELETE FROM role_permissions WHERE role_id IN (SELECT id FROM roles WHERE name = 'ADMIN');
--rollback DELETE FROM permission WHERE code IN ('ROLE_VIEW', 'PERMISSION_VIEW', 'ROLE_MANAGE');
--rollback DELETE FROM roles WHERE name IN ('BUYER', 'SELLER', 'ADMIN');
