--liquibase formatted sql

--changeset avazbek:005-init-categories
--comment: Product module — categories table

CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP,
    CONSTRAINT uq_categories_name UNIQUE (name)
);

--rollback DROP TABLE categories;

--changeset avazbek:006-init-product
--comment: Product module — product table (category optional, seller required)

CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)   NOT NULL,
    description VARCHAR(1000),
    price       NUMERIC(12, 2) NOT NULL,
    quantity    INTEGER        NOT NULL,
    category_id BIGINT,
    seller_id   BIGINT         NOT NULL,
    active      BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP      NOT NULL,
    updated_at  TIMESTAMP,
    CONSTRAINT fk_product_category FOREIGN KEY (category_id)
        REFERENCES categories (id),
    CONSTRAINT fk_product_seller FOREIGN KEY (seller_id)
        REFERENCES users (id)
);

--rollback DROP TABLE product;

--changeset avazbek:007-seed-product-permissions
--comment: Seed PRODUCT_CREATE/PRODUCT_MANAGE/CATEGORY_MANAGE and grant to SELLER/ADMIN

INSERT INTO permission (code, description, active, created_at)
VALUES ('PRODUCT_CREATE', 'Create products', true, CURRENT_TIMESTAMP),
       ('PRODUCT_MANAGE', 'Manage (update/delete) products', true, CURRENT_TIMESTAMP),
       ('CATEGORY_MANAGE', 'Manage product categories', true, CURRENT_TIMESTAMP);

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r,
     permission p
WHERE r.name = 'SELLER'
  AND p.code IN ('PRODUCT_CREATE', 'PRODUCT_MANAGE');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r,
     permission p
WHERE r.name = 'ADMIN'
  AND p.code IN ('PRODUCT_MANAGE', 'CATEGORY_MANAGE');

--rollback DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permission WHERE code IN ('PRODUCT_CREATE', 'PRODUCT_MANAGE', 'CATEGORY_MANAGE'));
--rollback DELETE FROM permission WHERE code IN ('PRODUCT_CREATE', 'PRODUCT_MANAGE', 'CATEGORY_MANAGE');

--changeset avazbek:008-add-category-parent
--comment: Categories can nest one level deep (parent/subcategory)

ALTER TABLE categories
    ADD COLUMN parent_id BIGINT;

ALTER TABLE categories
    ADD CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id)
        REFERENCES categories (id);

--rollback ALTER TABLE categories DROP CONSTRAINT fk_categories_parent;
--rollback ALTER TABLE categories DROP COLUMN parent_id;

--changeset avazbek:009-categories-name-partial-unique
--comment: Categories are soft-deleted too — name must be reusable after "deletion", same pattern as users.email

ALTER TABLE categories
    DROP CONSTRAINT uq_categories_name;

CREATE UNIQUE INDEX ux_categories_name_active ON categories (name) WHERE active = true;

--rollback DROP INDEX ux_categories_name_active;
--rollback ALTER TABLE categories ADD CONSTRAINT uq_categories_name UNIQUE (name);
