--liquibase formatted sql

--changeset avazbek:010-init-file-assets
--comment: File storage module — file_assets table (metadata for objects stored in MinIO)

CREATE TABLE file_assets
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_key        VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255),
    content_type       VARCHAR(100),
    uploaded_by        BIGINT,
    size_bytes         BIGINT,
    category           VARCHAR(30)  NOT NULL,
    active             BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMP    NOT NULL,
    updated_at         TIMESTAMP,
    CONSTRAINT uq_file_assets_storage_key UNIQUE (storage_key),
    CONSTRAINT fk_file_assets_uploaded_by FOREIGN KEY (uploaded_by)
        REFERENCES users (id)
);

--rollback DROP TABLE file_assets;
