--liquibase formatted sql

--changeset avazbek:011-add-product-images
--comment: Product image gallery — ordered list of file_assets attached to a product

CREATE TABLE product_images
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT    NOT NULL,
    file_asset_id BIGINT    NOT NULL,
    sort_order    INTEGER   NOT NULL DEFAULT 0,
    active        BOOLEAN   NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP,
    CONSTRAINT fk_product_images_product FOREIGN KEY (product_id)
        REFERENCES product (id),
    CONSTRAINT fk_product_images_file_asset FOREIGN KEY (file_asset_id)
        REFERENCES file_assets (id)
);

--rollback DROP TABLE product_images;
